// <auto-generated />
using CarroAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarroAPI.Migrations
{
    [DbContext(typeof(CarroAPIContext))]
    partial class CarroAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarroAPI.Models.AdicionaisCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("Carro Id");

                    b.Property<string>("OpcionaisCarros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Opcionais");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.ToTable("Opcionais", (string)null);
                });

            modelBuilder.Entity("CarroAPI.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano")
                        .HasColumnOrder(3);

                    b.Property<string>("CorDoCarro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cor")
                        .HasColumnOrder(4);

                    b.Property<string>("MarcaDoAutomovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Marca")
                        .HasColumnOrder(1);

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Modelo")
                        .HasColumnOrder(2);

                    b.Property<int>("QntdPortas")
                        .HasColumnType("int")
                        .HasColumnName("Portas")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("CarroAPI.Models.AdicionaisCarro", b =>
                {
                    b.HasOne("CarroAPI.Models.Carro", "Carro")
                        .WithMany("Adicionais")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("CarroAPI.Models.Carro", b =>
                {
                    b.Navigation("Adicionais");
                });
#pragma warning restore 612, 618
        }
    }
}
